### PR TITLE
Added real time data to pie chart

### PR DESCRIPTION
**Pull request by Halcyon905**
- Pulled medal data dynamically on medal page according to filters
 - Pulled audience data and displayed according age groups
 - Pulled overall medal data on home page

### CODE REVIEW

**Review by Supakrit65 — APPROVED** [review]
In a rush so no gif. : (

**Review by Savetang19 — APPROVED** [review]
image

Me approved

**Comment by GToidZ** [comment]
Looks good, however we'll need to fix things (conflict) before merging. @Halcyon905

**Comment by Halcyon905** [comment]
understood @GToidZ

**Review by Supakrit65 — APPROVED** [review]
Nice Again

**Review by MarojT — APPROVED** [review]
Nicee

**Pull request merged**
