### PR TITLE
Feat/bar chart component

### PR DESCRIPTION
**Pull request by RyukungG**
### What I have done in this Pull Request

-  Implement bar chart component
-  Fetch data from GET /audient
- Create sportid util file for convert sport id to sport name
- Implement bar chart section in audience page 
image
image
image

### CODE REVIEW

**Comment by Supakrit65** [comment]
image

There should be two felmale and 1 male for sport 1.

image

**Review by Supakrit65 — APPROVED** [review]
Oh nice

**Review by GToidZ — APPROVED** [review]
LGTM

**Review by Halcyon905 — APPROVED** [review]

**Pull request merged**
