### PR TITLE
Add two missing tables using filter key

### PR DESCRIPTION
**Pull request by GToidZ**
# Overview
* Adds two new tables: `SingleSport` and `SingleCountry`
* Each table will load data corresponding to the filter from the `Filter` component.
* The container that houses two new table has auto overflow but design can be changed later.

# Media
## Single Sport table with Diving as filter
Single Sport

### CODE REVIEW

**Review by Supakrit65 — APPROVED** [review]
### After ran it, It works. So Nice!

**Review by Savetang19 — APPROVED** [review]
image

LGTM! Me approve.

**Comment by GToidZ** [comment]
@Supakrit65 Sorry, I requested review again :sob:

**Comment by Supakrit65** [comment]
> @Supakrit65 Sorry, I requested review again 😭

Oh its fine

**Review by Supakrit65 — APPROVED** [review]
### After ran it, It works. So Nice!

**Review by RyukungG — APPROVED** [review]

**Pull request merged**
