### PR TITLE
Hotfix: sport icon not show on Safari

### PR DESCRIPTION
**Pull request by Savetang19**
## What I have done in this PR
- Add height in style to show icon

### Before
Screen Shot 2566-11-23 at 23 04 37
Screen Shot 2566-11-23 at 23 05 29

### After
Screen Shot 2566-11-23 at 23 05 49
Screen Shot 2566-11-23 at 23 05 44

### CODE REVIEW

**Review by GToidZ — APPROVED** [review]
LGTM! I'd always hate browser compatibility especially Safari, so you are being a savior here.

**Review by Hamiz5401 — APPROVED** [review]

**Review by Halcyon905 — APPROVED** [review]

**Review by RyukungG — APPROVED** [review]

**Review by MarojT — APPROVED** [review]
Nice

**Pull request merged**
