### PR TITLE
Create necessary base components for every pages

### PR DESCRIPTION
**Pull request by Savetang19**
### What I have done in this PR is:
- Create base components for every pages
- Add more important packages to the project by
  - `Axios` for making HTTP requests.
  - `ESlint` for lint check .
  - `TailwindCSS` for styling components.
- Provided routes for every pages by
  - Home pgae: `/`
  - Sports Page: `/sports`
  - Sports detail page: `/sports/:sportId` 
  - Medal page: `/medal`
  - Audience page: `/audience`
- Customize theme using Ant Design and config tailwind theme.

### CODE REVIEW

**Review by Supakrit65 — APPROVED** [review]
<h3 align="center">🚀 <b>Cloned and Ran</b> 🚀</h3>
<p align="center"><i>One thing to say...</i> <b style="color: #2980b9;">"Nice!"</b> 😎👍</p>
<p align="center">
  Celebration GIF
</p>
<p align="center">
  <sub>This is some seriously impressive work! Hats off to Savetang19! 🎩</sub>
</p>

**Review by GToidZ — APPROVED** [review]
Spectacular!

**Comment by RyukungG** [comment]
Goodๆ

**Review by RyukungG — APPROVED** [review]
Goodๆ

**Pull request merged**
