### PR TITLE
Test frontend for most of all components

### PR DESCRIPTION
**Pull request by Savetang19**
## What did I do in this PR?
- Use `Jest` to create a frontend component test.
- Here is a list of the components that were tested:
  - dropdownMenu
  - filterSportCountry
  - headerNavigation
  - medalIcon
  - mostInterestSports
  - searchBar
  - sportCard
  - sportIcons
  - totalAudienceNumber
- Note that components containing '@ant-design/plots' cannot be tested at this time.

### CODE REVIEW

**Review by Supakrit65 — APPROVED** [review]
I ran it and it seem to works and all tests are pass so good job. :)

**Review by Halcyon905 — APPROVED** [review]
seems good to me

**Review by Hamiz5401 — APPROVED** [review]
Looks good kub

**Review by RyukungG — APPROVED** [review]

**Review by GToidZ — APPROVED** [review]
No way! You guys did frontend testing!
no-way

**Pull request merged**
